[build]
  publish = "."

[build.processing]
  skip_processing = true

[build.processing.css]
  bundle = false
  minify = true

[build.processing.html]
  pretty_urls = true
  minify = true

[build.processing.images]
  compress = true
